name: atensystems
favicon: null
layout_spectrum: 0.22427273145876825
typography_spectrum: 0.5169057862367481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#004459'
    - '#bebebe'
    - '#ff0000'
    - '#ff8080'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.6074949207250029
purpose: []
